### ISSUE TITLE
Selfhosted Shellhub Terminal/SSH issue

### ISSUE THREAD

**Issue by suegy** [shellhub-io/shellhub#722]
Using Shellhub 0.5.0

When self-hosting shellhub on a Ubuntu Server I cannot use ports 80 and 22 for shellhub.
The shellhub starts in the docker container with custom ports correctly and logging in and adding a device everything works.

Starting a terminal session to an agent does not work and terminal does not log in. no information in ssh log as well.

ssh connection with the sshid also results in a failed connection.

ssh agent log:
```
2021/02/15 12:46:24 http: superfluous response.WriteHeader call from github.com/shellhub-io/shellhub/pkg/httptunnel.(*Tunnel).Router.func1 (httptunnel.go:61)
time="2021-02-15T12:46:27Z" level=info msg="Handling session request" session=<removed> target=<removed>
time="2021-02-15T12:46:27Z" level=error msg="Invalid session target" session=<removed>
2021/02/15 12:46:35 http: superfluous response.WriteHeader call from github.com/shellhub-io/shellhub/pkg/httptunnel.(*Tunnel).Router.func1 (httptunnel.go:61)
```

**Comment by gustavosbarreto** [comment]
This has already been fixed in master branch. See #699

**Comment by suegy** [comment]
what is the current ETA for the next release or is there a way to test a patch on 0.5.1?

**Comment by gustavosbarreto** [comment]
> what is the current ETA for the next release or is there a way to test a patch on 0.5.1?

We will release a new version next week

**Comment by otavio** [comment]
I'm closing this as the issue has been already fixed.

**Comment by suegy** [comment]
Testing in v0.6.0 shows the issue is still there. 


When trying to connect to the agent through ssh:
```ssh usr@<sshid> -P 2223```

the server locks up the ssh port and gives following message on the cmd:

```ssh_dispatch_run_fatal: Connection to <IP> port 22: Connection timed out```

in ```.env.override``` the ssh port is set to 2223

**Comment by gustavosbarreto** [comment]
> `ssh usr@<sshid> -P 2223`

Aren't you confusing `-P` with `-p`?

> ssh_dispatch_run_fatal: Connection to <IP> port 22: Connection timed out

I don't recognize this log message being from ShellHub.

**Comment by suegy** [comment]
Yes sorry this should have been -p.

The log message is not from shellhub directly but it seems that the agent is calling calling the server on the wrong port more than once until the fail2ban adds my IP to the blacklist and ssh terminates with a connection error.

**Comment by gustavosbarreto** [comment]
> Yes sorry this should have been -p.
> 
> The log message is not from shellhub directly but it seems that the gateway is calling calling the server on the wrong port more than once until the fail2ban adds my IP to the blacklist and ssh terminates with a connection error.

I cannot reproduce this issue here with custom SSH and HTTP ports

**Comment by otavio** [comment]
@suegy please share the override file you are using with the `docker-compose`.

**Comment by suegy** [comment]
here is the ```.env.override```:
```
# The HTTP listen port for the ShellHub web-based GUI, API and Reverse SSH tunn$
# Values: any free port on host
SHELLHUB_HTTP_PORT=8081

# The HTTPS listen port for the ShellHub web-based GUI, API and Reverse SSH tun$
# Values: any free port on host
SHELLHUB_HTTPS_PORT=8082

# The SSH listen port for incoming SSH connections to devices
# Values: any free port on host
SHELLHUB_SSH_PORT=2222

# Domain of the server
# NOTICE: Only required if automatic HTTPS is enabled
# Values: a valid domain name
SHELLHUB_DOMAIN=<url>
```
and here the ```docker.compose.override.yml```:
```

version: '3.7'
services:
  ssh:
    restart: unless-stopped
  ui:
    restart: unless-stopped
  gateway:
    restart: unless-stopped
  mongo:
    restart: unless-stopped
    volumes:
      - /usr/local/mongo/data:/data/db
```
I did not modify any other shellhub files

**Comment by gustavosbarreto** [comment]
@suegy are you sure you haven't' blocked by fail2ban?

**Comment by suegy** [comment]
Yes I do get blocked by fail2ban upon trying to connect on ssh as the connections seems to fail and retry to quick.

**Comment by otavio** [comment]
@suegy as this is a fail2ban issue, what do you think we should do at ShellHub side?

**Comment by otavio** [comment]
This seems to be an issue due to the use of the `fail2ban` so we're closing it. If need, please reopen.
